-- MySQL Script generated by MySQL Workbench
-- 06/22/15 09:41:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema musiclibary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musiclibary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musiclibary` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `musiclibary` ;

-- -----------------------------------------------------
-- Table `musiclibary`.`MusicInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiclibary`.`MusicInfo` (
  `idMusicInfo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NULL,
  `Artist` VARCHAR(200) NULL,
  `Album` VARCHAR(200) NULL,
  `FileDir` VARCHAR(400) NULL,
  `InfoDir` VARCHAR(400) NULL,
  PRIMARY KEY (`idMusicInfo`, `Title`, `Album`, `Artist`),
  UNIQUE INDEX `idMusicInfo_UNIQUE` (`idMusicInfo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musiclibary`.`HashTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musiclibary`.`HashTable` (
  `idHashTable` INT NOT NULL AUTO_INCREMENT,
  `Hash` INT NOT NULL,
  `ID` INT NOT NULL,
  `Time` INT NOT NULL,
  PRIMARY KEY (`idHashTable`),
  INDEX `Hash` (`Hash` ASC)  KEY_BLOCK_SIZE=1)
ENGINE = InnoDB
ROW_FORMAT = FIXED;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
